<a href="https://colab.research.google.com/github/shake345/pre_treatment/blob/main/pre_treatment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [12]:
import pandas as pd
%cd /content/drive/MyDrive/前処理大全/

/content/drive/MyDrive/前処理大全

In [13]:
reserve_tb = pd.read_csv('reserve.csv', encoding='utf-8')

In [14]:
# 必要なカラムを抽出
reserve_tb[['reserve_id','hotel_id','customer_id','reserve_datetime','checkin_date','checkin_time','checkout_date']]
print(reserve_tb.head())

  reserve_id hotel_id customer_id     reserve_datetime checkin_date  \
0         r1     h_75         c_1  2016-03-06 13:09:42   2016-03-26
1         r2    h_219         c_1  2016-07-16 23:39:55   2016-07-20
2         r3    h_179         c_1  2016-09-24 10:03:17   2016-10-19
3         r4    h_214         c_1  2017-03-08 03:20:10   2017-03-29
4         r5     h_16         c_1  2017-09-05 19:50:37   2017-09-22

  checkin_time checkout_date  people_num  total_price
0     10:00:00    2016-03-29           4        97200
1     11:30:00    2016-07-21           2        20600
2     09:00:00    2016-10-22           2        33600
3     11:00:00    2017-03-30           4       194400
4     10:30:00    2017-09-23           3        68100

In [15]:
# 条件による抽出
query_table = reserve_tb.query('"2016-10-12" <= checkout_date <= "2016-10-13"')
query_table.head()

,reserve_id,hotel_id,customer_id,reserve_datetime,checkin_date,checkin_time,checkout_date,people_num,total_price
347,r348,h_161,c_82,2016-09-22 22:29:52,2016-10-10,10:30:00,2016-10-12,2,178400
587,r588,h_263,c_143,2016-09-25 20:07:03,2016-10-11,09:00:00,2016-10-12,4,91600
1254,r1255,h_148,c_305,2016-09-12 15:32:03,2016-10-11,11:30:00,2016-10-12,4,39200
1480,r1481,h_116,c_364,2016-09-17 17:45:39,2016-10-11,11:30:00,2016-10-13,4,107200
1546,r1547,h_149,c_377,2016-09-27 08:19:24,2016-10-10,11:00:00,2016-10-13,2,153600

In [16]:
# ランダムサンプリング
samp_table = reserve_tb.sample(frac=0.5)
samp_table

,reserve_id,hotel_id,customer_id,reserve_datetime,checkin_date,checkin_time,checkout_date,people_num,total_price
3963,r3964,h_89,c_985,2016-10-24 19:38:46,2016-11-11,09:00:00,2016-11-12,3,26400
217,r218,h_249,c_50,2016-06-16 15:33:26,2016-06-19,12:00:00,2016-06-20,1,48700
1222,r1223,h_19,c_299,2016-06-19 12:00:31,2016-06-23,11:00:00,2016-06-25,3,72000
973,r974,h_89,c_239,2017-11-28 23:28:16,2017-12-03,10:30:00,2017-12-05,3,52800
1978,r1979,h_274,c_498,2016-03-24 06:54:54,2016-04-18,11:30:00,2016-04-21,1,47100
...,...,...,...,...,...,...,...,...,...
1502,r1503,h_206,c_369,2017-06-26 16:01:47,2017-07-25,10:00:00,2017-07-27,4,193600
1419,r1420,h_274,c_346,2016-05-31 09:53:05,2016-06-30,10:30:00,2016-07-01,2,31400
3335,r3336,h_34,c_835,2016-08-28 18:18:09,2016-09-08,09:30:00,2016-09-09,3,25500
1617,r1618,h_300,c_396,2016-01-13 16:53:07,2016-01-18,09:30:00,2016-01-20,3,97800
220,r221,h_231,c_51,2016-02-08 14:40:50,2016-02-19,10:30:00,2016-02-20,4,58400

In [17]:
# IDごとのサンプリング
# sample関数を利用するために、pd.Series（pandasのリストオブジェクト）に変換
target = pd.Series(reserve_tb['customer_id'].unique()).sample(frac=0.5)
reserve_tb[reserve_tb['customer_id'].isin(target)]
reserve_tb.head()

,reserve_id,hotel_id,customer_id,reserve_datetime,checkin_date,checkin_time,checkout_date,people_num,total_price
0,r1,h_75,c_1,2016-03-06 13:09:42,2016-03-26,10:00:00,2016-03-29,4,97200
1,r2,h_219,c_1,2016-07-16 23:39:55,2016-07-20,11:30:00,2016-07-21,2,20600
2,r3,h_179,c_1,2016-09-24 10:03:17,2016-10-19,09:00:00,2016-10-22,2,33600
3,r4,h_214,c_1,2017-03-08 03:20:10,2017-03-29,11:00:00,2017-03-30,4,194400
4,r5,h_16,c_1,2017-09-05 19:50:37,2017-09-22,10:30:00,2017-09-23,3,68100

In [18]:
# カウントとユニークカウント
# reserve_idを対象にcount関数を適用
# customer_idを対象にnunique関数を適用
result = reserve_tb.groupby('hotel_id').agg({'reserve_id': 'count', 'customer_id':'nunique'})

result.reset_index(inplace=True)
result.columns = ['hotel_id','rsv_cnt', 'cus_cnt']
result.head()

  hotel_id  rsv_cnt  cus_cnt
0      h_1       10       10
1     h_10        3        3
2    h_100       20       19
3    h_101       17       17
4    h_102       13       13

In [19]:
# 合計値
result_sum = reserve_tb.groupby(['hotel_id','people_num'])['total_price'].sum().reset_index()

result_sum.rename(columns={'total_price': 'price_sum'}, inplace=True)
result_sum.head()

  hotel_id  people_num  price_sum
0      h_1           1     156600
1      h_1           2     156600
2      h_1           3     391500
3      h_1           4     417600
4     h_10           1      11200

In [20]:
# 代表値
import numpy as np
result_value = reserve_tb.groupby('hotel_id').agg({'total_price': ['max','min','mean','median',lambda x: np.percentile(x, q=20)]}).reset_index()

result_value.columns = ['hotel_id',' price_max', 'price_min', 'price_mean', 'price_median', 'price_20per']
result_value.head()

  hotel_id   price_max  price_min     price_mean  price_median  price_20per
0      h_1      208800      26100  112230.000000      104400.0      73080.0
1     h_10       67200      11200   42933.333333       50400.0      26880.0
2    h_100       57600       4800   27600.000000       28800.0       9600.0
3    h_101      168000      14000   75764.705882       56000.0      30800.0
4    h_102       72000      12000   32769.230769       24000.0      18000.0

In [21]:
# 分散地と標準偏差値
result_var_std = reserve_tb.groupby('hotel_id').agg({'total_price': ['var','std']}).reset_index()
result_var_std.columns = ['hotel_id','price_var','price_std']

# データ件が1件の場合は、分散地と標準偏差値がnaになっているので、0に置き換える
result_var_std.fillna(0, inplace=True)
result_var_std.head()

  hotel_id     price_var     price_std
0      h_1  3.186549e+09  56449.526127
1     h_10  8.258133e+08  28736.968061
2    h_100  3.198316e+08  17883.835689
3    h_101  2.402441e+09  49014.703676
4    h_102  3.576923e+08  18912.755159

In [23]:
# 最頻値の算出
reserve_tb['total_price'].round(-3).mode()

0    10000
1    20000
2    40000
Name: total_price, dtype: int64