<a href="https://colab.research.google.com/github/shake345/pre_treatment/blob/main/pre_treatment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
%cd /content/drive/MyDrive/前処理大全/

/content/drive/MyDrive/前処理大全

In [4]:
reserve_tb = pd.read_csv('reserve.csv', encoding='utf-8')

In [5]:
# 必要なカラムを抽出
reserve_tb[['reserve_id','hotel_id','customer_id','reserve_datetime','checkin_date','checkin_time','checkout_date']]
print(reserve_tb.head())

  reserve_id hotel_id customer_id     reserve_datetime checkin_date  \
0         r1     h_75         c_1  2016-03-06 13:09:42   2016-03-26
1         r2    h_219         c_1  2016-07-16 23:39:55   2016-07-20
2         r3    h_179         c_1  2016-09-24 10:03:17   2016-10-19
3         r4    h_214         c_1  2017-03-08 03:20:10   2017-03-29
4         r5     h_16         c_1  2017-09-05 19:50:37   2017-09-22

  checkin_time checkout_date  people_num  total_price
0     10:00:00    2016-03-29           4        97200
1     11:30:00    2016-07-21           2        20600
2     09:00:00    2016-10-22           2        33600
3     11:00:00    2017-03-30           4       194400
4     10:30:00    2017-09-23           3        68100

In [7]:
# 条件による抽出
query_table = reserve_tb.query('"2016-10-12" <= checkout_date <= "2016-10-13"')
query_table.head()

,reserve_id,hotel_id,customer_id,reserve_datetime,checkin_date,checkin_time,checkout_date,people_num,total_price
347,r348,h_161,c_82,2016-09-22 22:29:52,2016-10-10,10:30:00,2016-10-12,2,178400
587,r588,h_263,c_143,2016-09-25 20:07:03,2016-10-11,09:00:00,2016-10-12,4,91600
1254,r1255,h_148,c_305,2016-09-12 15:32:03,2016-10-11,11:30:00,2016-10-12,4,39200
1480,r1481,h_116,c_364,2016-09-17 17:45:39,2016-10-11,11:30:00,2016-10-13,4,107200
1546,r1547,h_149,c_377,2016-09-27 08:19:24,2016-10-10,11:00:00,2016-10-13,2,153600

In [8]:
# ランダムサンプリング
samp_table = reserve_tb.sample(frac=0.5)
samp_table

,reserve_id,hotel_id,customer_id,reserve_datetime,checkin_date,checkin_time,checkout_date,people_num,total_price
3581,r3582,h_248,c_889,2016-08-29 06:09:42,2016-09-19,10:00:00,2016-09-22,1,51600
1154,r1155,h_178,c_281,2016-06-14 10:03:34,2016-07-13,11:00:00,2016-07-15,1,42000
3910,r3911,h_183,c_972,2017-05-21 10:01:22,2017-05-23,09:30:00,2017-05-25,3,59400
2368,r2369,h_106,c_596,2016-03-09 17:45:06,2016-03-20,09:00:00,2016-03-22,3,133200
2205,r2206,h_102,c_549,2016-12-17 13:43:31,2017-01-05,10:00:00,2017-01-06,4,24000
...,...,...,...,...,...,...,...,...,...
359,r360,h_295,c_83,2017-09-14 16:14:51,2017-09-18,12:30:00,2017-09-20,2,22400
695,r696,h_277,c_170,2016-08-09 01:57:52,2016-08-24,11:00:00,2016-08-27,4,157200
2240,r2241,h_256,c_560,2016-10-03 13:45:55,2016-10-05,09:30:00,2016-10-08,4,414000
2305,r2306,h_26,c_577,2016-04-13 04:54:24,2016-05-09,10:30:00,2016-05-11,2,199600
1879,r1880,h_269,c_465,2016-10-10 10:53:13,2016-10-31,12:30:00,2016-11-01,4,270400