<a href="https://colab.research.google.com/github/shake345/pre_treatment/blob/main/pre_treatment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [1]:
import pandas as pd
%cd /content/drive/MyDrive/前処理大全/

/content/drive/MyDrive/前処理大全

In [2]:
reserve_tb = pd.read_csv('reserve.csv', encoding='utf-8')

In [3]:
# 必要なカラムを抽出
reserve_tb[['reserve_id','hotel_id','customer_id','reserve_datetime','checkin_date','checkin_time','checkout_date']]
print(reserve_tb.head())

  reserve_id hotel_id customer_id     reserve_datetime checkin_date  \
0         r1     h_75         c_1  2016-03-06 13:09:42   2016-03-26
1         r2    h_219         c_1  2016-07-16 23:39:55   2016-07-20
2         r3    h_179         c_1  2016-09-24 10:03:17   2016-10-19
3         r4    h_214         c_1  2017-03-08 03:20:10   2017-03-29
4         r5     h_16         c_1  2017-09-05 19:50:37   2017-09-22

  checkin_time checkout_date  people_num  total_price
0     10:00:00    2016-03-29           4        97200
1     11:30:00    2016-07-21           2        20600
2     09:00:00    2016-10-22           2        33600
3     11:00:00    2017-03-30           4       194400
4     10:30:00    2017-09-23           3        68100

In [4]:
# 条件による抽出
query_table = reserve_tb.query('"2016-10-12" <= checkout_date <= "2016-10-13"')
query_table.head()

,reserve_id,hotel_id,customer_id,reserve_datetime,checkin_date,checkin_time,checkout_date,people_num,total_price
347,r348,h_161,c_82,2016-09-22 22:29:52,2016-10-10,10:30:00,2016-10-12,2,178400
587,r588,h_263,c_143,2016-09-25 20:07:03,2016-10-11,09:00:00,2016-10-12,4,91600
1254,r1255,h_148,c_305,2016-09-12 15:32:03,2016-10-11,11:30:00,2016-10-12,4,39200
1480,r1481,h_116,c_364,2016-09-17 17:45:39,2016-10-11,11:30:00,2016-10-13,4,107200
1546,r1547,h_149,c_377,2016-09-27 08:19:24,2016-10-10,11:00:00,2016-10-13,2,153600

In [5]:
# ランダムサンプリング
samp_table = reserve_tb.sample(frac=0.5)
samp_table

,reserve_id,hotel_id,customer_id,reserve_datetime,checkin_date,checkin_time,checkout_date,people_num,total_price
500,r501,h_191,c_118,2018-02-18 09:19:20,2018-02-27,12:30:00,2018-03-02,3,371700
1338,r1339,h_201,c_327,2016-07-12 00:58:18,2016-08-06,10:00:00,2016-08-08,1,17800
596,r597,h_196,c_145,2016-04-16 00:06:45,2016-05-01,09:30:00,2016-05-03,4,188000
3611,r3612,h_214,c_901,2016-06-12 13:55:44,2016-06-22,11:30:00,2016-06-23,3,145800
1354,r1355,h_45,c_332,2016-09-28 16:40:20,2016-09-28,12:30:00,2016-09-30,1,20000
...,...,...,...,...,...,...,...,...,...
1179,r1180,h_250,c_288,2016-07-23 14:17:11,2016-08-02,12:30:00,2016-08-04,4,206400
3311,r3312,h_35,c_830,2017-06-22 14:58:29,2017-07-12,11:00:00,2017-07-13,1,3500
3912,r3913,h_70,c_973,2016-06-04 01:52:22,2016-06-18,09:30:00,2016-06-20,4,62400
3473,r3474,h_136,c_865,2017-07-24 02:06:53,2017-08-02,12:00:00,2017-08-05,1,62100
197,r198,h_56,c_46,2016-07-05 14:16:55,2016-07-23,12:30:00,2016-07-24,2,63800

In [7]:
# IDごとのサンプリング
# sample関数を利用するために、pd.Series（pandasのリストオブジェクト）に変換
target = pd.Series(reserve_tb['customer_id'].unique()).sample(frac=0.5)
reserve_tb[reserve_tb['customer_id'].isin(target)]
reserve_tb.head()

,reserve_id,hotel_id,customer_id,reserve_datetime,checkin_date,checkin_time,checkout_date,people_num,total_price
0,r1,h_75,c_1,2016-03-06 13:09:42,2016-03-26,10:00:00,2016-03-29,4,97200
1,r2,h_219,c_1,2016-07-16 23:39:55,2016-07-20,11:30:00,2016-07-21,2,20600
2,r3,h_179,c_1,2016-09-24 10:03:17,2016-10-19,09:00:00,2016-10-22,2,33600
3,r4,h_214,c_1,2017-03-08 03:20:10,2017-03-29,11:00:00,2017-03-30,4,194400
4,r5,h_16,c_1,2017-09-05 19:50:37,2017-09-22,10:30:00,2017-09-23,3,68100

In [8]:
# カウントとユニークカウント
# reserve_idを対象にcount関数を適用
# customer_idを対象にnunique関数を適用
result = reserve_tb.groupby('hotel_id').agg({'reserve_id': 'count', 'customer_id':'nunique'})

result.reset_index(inplace=True)
result.columns = ['hotel_id','rsv_cnt', 'cus_cnt']
result.head()

  hotel_id  rsv_cnt  cus_cnt
0      h_1       10       10
1     h_10        3        3
2    h_100       20       19
3    h_101       17       17
4    h_102       13       13

In [9]:
# 合計値
result_sum = reserve_tb.groupby(['hotel_id','people_num'])['total_price'].sum().reset_index()

result_sum.rename(columns={'total_price': 'price_sum'}, inplace=True)
result_sum.head()

  hotel_id  people_num  price_sum
0      h_1           1     156600
1      h_1           2     156600
2      h_1           3     391500
3      h_1           4     417600
4     h_10           1      11200