<a href="https://colab.research.google.com/github/shake345/pre_treatment/blob/main/pre_treatment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [37]:
import pandas as pd
%cd /content/drive/MyDrive/前処理大全/

/content/drive/MyDrive/前処理大全

In [38]:
reserve_tb = pd.read_csv('reserve.csv', encoding='utf-8')

In [39]:
# 必要なカラムを抽出
reserve_tb[['reserve_id','hotel_id','customer_id','reserve_datetime','checkin_date','checkin_time','checkout_date']]
print(reserve_tb.head())

  reserve_id hotel_id customer_id     reserve_datetime checkin_date  \
0         r1     h_75         c_1  2016-03-06 13:09:42   2016-03-26
1         r2    h_219         c_1  2016-07-16 23:39:55   2016-07-20
2         r3    h_179         c_1  2016-09-24 10:03:17   2016-10-19
3         r4    h_214         c_1  2017-03-08 03:20:10   2017-03-29
4         r5     h_16         c_1  2017-09-05 19:50:37   2017-09-22

  checkin_time checkout_date  people_num  total_price
0     10:00:00    2016-03-29           4        97200
1     11:30:00    2016-07-21           2        20600
2     09:00:00    2016-10-22           2        33600
3     11:00:00    2017-03-30           4       194400
4     10:30:00    2017-09-23           3        68100

In [40]:
# 条件による抽出
query_table = reserve_tb.query('"2016-10-12" <= checkout_date <= "2016-10-13"')
query_table.head()

,reserve_id,hotel_id,customer_id,reserve_datetime,checkin_date,checkin_time,checkout_date,people_num,total_price
347,r348,h_161,c_82,2016-09-22 22:29:52,2016-10-10,10:30:00,2016-10-12,2,178400
587,r588,h_263,c_143,2016-09-25 20:07:03,2016-10-11,09:00:00,2016-10-12,4,91600
1254,r1255,h_148,c_305,2016-09-12 15:32:03,2016-10-11,11:30:00,2016-10-12,4,39200
1480,r1481,h_116,c_364,2016-09-17 17:45:39,2016-10-11,11:30:00,2016-10-13,4,107200
1546,r1547,h_149,c_377,2016-09-27 08:19:24,2016-10-10,11:00:00,2016-10-13,2,153600

In [41]:
# ランダムサンプリング
samp_table = reserve_tb.sample(frac=0.5)
samp_table

,reserve_id,hotel_id,customer_id,reserve_datetime,checkin_date,checkin_time,checkout_date,people_num,total_price
4014,r4015,h_225,c_996,2016-12-03 21:40:17,2016-12-22,11:30:00,2016-12-23,3,21600
1551,r1552,h_106,c_378,2016-11-28 07:57:38,2016-12-13,11:00:00,2016-12-15,4,177600
753,r754,h_137,c_181,2017-03-19 19:13:56,2017-03-25,11:00:00,2017-03-26,3,18600
2755,r2756,h_120,c_695,2016-09-15 00:14:14,2016-10-01,11:00:00,2016-10-03,4,347200
2383,r2384,h_15,c_599,2017-11-29 23:41:20,2017-12-26,11:30:00,2017-12-29,4,51600
...,...,...,...,...,...,...,...,...,...
2731,r2732,h_130,c_689,2016-04-30 19:58:28,2016-05-13,12:00:00,2016-05-15,1,50400
1485,r1486,h_252,c_365,2016-09-13 19:49:25,2016-10-03,12:00:00,2016-10-04,2,44400
2531,r2532,h_162,c_632,2016-12-24 06:56:51,2017-01-16,09:30:00,2017-01-19,1,31500
3314,r3315,h_156,c_831,2016-05-26 17:01:45,2016-06-20,12:00:00,2016-06-23,2,110400
3447,r3448,h_265,c_861,2016-05-24 16:46:47,2016-06-03,12:30:00,2016-06-05,1,37200

In [42]:
# IDごとのサンプリング
# sample関数を利用するために、pd.Series（pandasのリストオブジェクト）に変換
target = pd.Series(reserve_tb['customer_id'].unique()).sample(frac=0.5)
reserve_tb[reserve_tb['customer_id'].isin(target)]
reserve_tb.head()

,reserve_id,hotel_id,customer_id,reserve_datetime,checkin_date,checkin_time,checkout_date,people_num,total_price
0,r1,h_75,c_1,2016-03-06 13:09:42,2016-03-26,10:00:00,2016-03-29,4,97200
1,r2,h_219,c_1,2016-07-16 23:39:55,2016-07-20,11:30:00,2016-07-21,2,20600
2,r3,h_179,c_1,2016-09-24 10:03:17,2016-10-19,09:00:00,2016-10-22,2,33600
3,r4,h_214,c_1,2017-03-08 03:20:10,2017-03-29,11:00:00,2017-03-30,4,194400
4,r5,h_16,c_1,2017-09-05 19:50:37,2017-09-22,10:30:00,2017-09-23,3,68100

In [43]:
# カウントとユニークカウント
# reserve_idを対象にcount関数を適用
# customer_idを対象にnunique関数を適用
result = reserve_tb.groupby('hotel_id').agg({'reserve_id': 'count', 'customer_id':'nunique'})

result.reset_index(inplace=True)
result.columns = ['hotel_id','rsv_cnt', 'cus_cnt']
result.head()

  hotel_id  rsv_cnt  cus_cnt
0      h_1       10       10
1     h_10        3        3
2    h_100       20       19
3    h_101       17       17
4    h_102       13       13

In [44]:
# 合計値
result_sum = reserve_tb.groupby(['hotel_id','people_num'])['total_price'].sum().reset_index()

result_sum.rename(columns={'total_price': 'price_sum'}, inplace=True)
result_sum.head()

  hotel_id  people_num  price_sum
0      h_1           1     156600
1      h_1           2     156600
2      h_1           3     391500
3      h_1           4     417600
4     h_10           1      11200

In [45]:
# 代表値
import numpy as np
result_value = reserve_tb.groupby('hotel_id').agg({'total_price': ['max','min','mean','median',lambda x: np.percentile(x, q=20)]}).reset_index()

result_value.columns = ['hotel_id',' price_max', 'price_min', 'price_mean', 'price_median', 'price_20per']
result_value.head()

  hotel_id   price_max  price_min     price_mean  price_median  price_20per
0      h_1      208800      26100  112230.000000      104400.0      73080.0
1     h_10       67200      11200   42933.333333       50400.0      26880.0
2    h_100       57600       4800   27600.000000       28800.0       9600.0
3    h_101      168000      14000   75764.705882       56000.0      30800.0
4    h_102       72000      12000   32769.230769       24000.0      18000.0

In [46]:
# 分散地と標準偏差値
result_var_std = reserve_tb.groupby('hotel_id').agg({'total_price': ['var','std']}).reset_index()
result_var_std.columns = ['hotel_id','price_var','price_std']

# データ件が1件の場合は、分散地と標準偏差値がnaになっているので、0に置き換える
result_var_std.fillna(0, inplace=True)
result_var_std.head()

  hotel_id     price_var     price_std
0      h_1  3.186549e+09  56449.526127
1     h_10  8.258133e+08  28736.968061
2    h_100  3.198316e+08  17883.835689
3    h_101  2.402441e+09  49014.703676
4    h_102  3.576923e+08  18912.755159

In [47]:
# 最頻値の算出
reserve_tb['total_price'].round(-3).mode()

0    10000
1    20000
2    40000
Name: total_price, dtype: int64

In [48]:
# 順位の算出
# rank関数は文字列に対応していないため、datetime型に変換
reserve_tb['reserve_datetime'] = pd.to_datetime(reserve_tb['reserve_datetime'], format='%Y-%m-%d %H:%M:%S')

# method='first': 同率は登録順にランク付けされる
reserve_tb['log_no'] = reserve_tb.groupby('customer_id')['reserve_datetime'].rank(ascending=True,method='first')
reserve_tb.head()

,reserve_id,hotel_id,customer_id,reserve_datetime,checkin_date,checkin_time,checkout_date,people_num,total_price,log_no
0,r1,h_75,c_1,2016-03-06 13:09:42,2016-03-26,10:00:00,2016-03-29,4,97200,1.0
1,r2,h_219,c_1,2016-07-16 23:39:55,2016-07-20,11:30:00,2016-07-21,2,20600,2.0
2,r3,h_179,c_1,2016-09-24 10:03:17,2016-10-19,09:00:00,2016-10-22,2,33600,3.0
3,r4,h_214,c_1,2017-03-08 03:20:10,2017-03-29,11:00:00,2017-03-30,4,194400,4.0
4,r5,h_16,c_1,2017-09-05 19:50:37,2017-09-22,10:30:00,2017-09-23,3,68100,5.0

In [49]:
# ランキング
reserve_rank = reserve_tb.groupby('hotel_id').size().reset_index()
reserve_rank.columns = ['hotel_id','rsv_cnt']

# method='min':同率は同じランク（最小単位）を付与
reserve_rank['rsv_cnt_rank'] = reserve_rank['rsv_cnt'].rank(ascending=False, method='min')
reserve_rank = reserve_rank[['hotel_id','rsv_cnt_rank']]

In [50]:
reserve_rank_sorted = reserve_rank.sort_values(by='rsv_cnt_rank', ascending=True)
display(reserve_rank_sorted.head())

    hotel_id  rsv_cnt_rank
158    h_241           1.0
50     h_144           2.0
231     h_37           3.0
48     h_142           3.0
87     h_178           5.0

In [54]:
# マスタテーブルの結合
hotel_tb = pd.read_csv('hotel.csv', encoding='utf-8')
display(hotel_tb.head())

pd.merge(reserve_tb.query('people_num==1'), hotel_tb.query('is_business'), on='hotel_id', how='inner')

,hotel_id,base_price,big_area_name,small_area_name,hotel_latitude,hotel_longitude,is_business
0,h_1,26100,D,D-2,43.064569,141.511397,True
1,h_2,26400,A,A-1,35.715320,139.939446,True
2,h_3,41300,E,E-4,35.281572,136.988565,False
3,h_4,5200,C,C-3,38.431293,140.795615,False
4,h_5,13500,G,G-3,33.597291,130.533872,True

,reserve_id,hotel_id,customer_id,reserve_datetime,checkin_date,checkin_time,checkout_date,people_num,total_price,log_no,base_price,big_area_name,small_area_name,hotel_latitude,hotel_longitude,is_business
0,r7,h_256,c_1,2017-12-29 10:38:36,2018-01-25,10:30:00,2018-01-28,1,103500,7.0,34500,C,C-1,38.237294,140.696131,True
1,r11,h_183,c_2,2016-11-19 12:49:10,2016-12-08,11:00:00,2016-12-11,1,29700,3.0,9900,G,G-4,33.595248,130.633567,True
2,r13,h_223,c_2,2017-10-19 03:03:30,2017-10-21,09:30:00,2017-10-23,1,137000,5.0,68500,C,C-2,38.329097,140.698165,True
3,r18,h_132,c_3,2016-10-22 02:18:48,2016-11-12,12:00:00,2016-11-13,1,20400,2.0,20400,C,C-1,38.231842,140.797268,True
4,r25,h_277,c_4,2016-03-28 07:17:34,2016-04-07,10:30:00,2016-04-10,1,39300,1.0,13100,C,C-1,38.233985,140.795603,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
441,r3999,h_72,c_993,2016-06-09 04:35:48,2016-07-04,12:00:00,2016-07-07,1,29100,2.0,9700,B,B-2,35.545712,139.596157,True
442,r4001,h_253,c_993,2017-01-20 18:50:35,2017-02-10,11:00:00,2017-02-12,1,10400,4.0,5200,C,C-3,38.430220,140.696571,True
443,r4005,h_150,c_994,2016-03-25 11:51:26,2016-04-02,09:00:00,2016-04-03,1,25200,1.0,25200,B,B-2,35.546229,139.693687,True
444,r4011,h_137,c_995,2017-08-13 19:23:48,2017-09-07,09:30:00,2017-09-09,1,12400,6.0,6200,F,F-1,34.538252,132.469507,True
445,r4030,h_117,c_1000,2016-06-06 08:16:51,2016-07-06,09:00:00,2016-07-09,1,44100,2.0,14700,A,A-3,35.912979,139.832314,True

In [62]:
# 条件別に結合するマスタテーブルを切り替え
hotel_area_tb = hotel_tb.groupby(['big_area_name','small_area_name']).size().reset_index()
hotel_area_tb.columns = ['big_area_name','small_area_name','hotel_cnt']
display(hotel_area_tb)

# 自ホテルを除いてhotel_cntが20以上の場合はsmall_area_name, それ以外の場合はbig_area_nameを付与したい
hotel_area_tb['join_area_id'] = np.where(hotel_area_tb['hotel_cnt'] -1 >= 20, hotel_area_tb['small_area_name'], hotel_area_tb['big_area_name'])
hotel_area_tb = hotel_area_tb[['small_area_name','join_area_id']]
display(hotel_area_tb.head())

   big_area_name small_area_name  hotel_cnt
0              A             A-1         35
1              A             A-3         30
2              B             B-1         15
3              B             B-2         18
4              B             B-3         19
5              C             C-1         25
6              C             C-2         30
7              C             C-3         21
8              D             D-1          7
9              D             D-2          7
10             D             D-3          7
11             D             D-4          5
12             E             E-1          8
13             E             E-2          5
14             E             E-3          4
15             E             E-4          9
16             F             F-1          6
17             F             F-2          5
18             F             F-3         11
19             F             F-4          7
20             G             G-1          9
21             G             G-2          4
22             G             G-3          6
23             G             G-4          7

  small_area_name join_area_id
0             A-1          A-1
1             A-3          A-3
2             B-1            B
3             B-2            B
4             B-3            B

In [63]:
hotel_merge = pd.merge(hotel_tb, hotel_area_tb, on='small_area_name')
hotel_merge = hotel_merge[['hotel_id','join_area_id']]
display(hotel_merge.head())

  hotel_id join_area_id
0      h_1            D
1      h_2          A-1
2      h_3            E
3      h_4          C-3
4      h_5            G

In [ ]:
recommend_hotel_mst = pd.concat([

    hotel_tb[['small_area_name','hotel_id']].rename(columns={'small_area_name': 'join_area_id'}, inplace=False),
    hotel_tb[['big_area_name','hotel_id']].rename(columns={'big_area_name': 'join_area_id'}, inplace=False)
])